---
title: "Quantmod IV"
author: "William Ng"
date: "3/4/2019"
output: html_document
---

```{r setup, include FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(PerformanceAnalytics)
library(quantmod)
library(tidyverse)
options("getSymbols.yahoo.warning" = FALSE)
```


### Pull down stock Data for MSFT using Get Symbols

```{r}

getSymbols("MSFT")
price <- MSFT$MSFT.Close    # Close price
r <- price/Lag(price) - 1   # % price change
delta <- 0.005              # threshold
signal <- c(0)              # first data has no signal

# Loop over all trading days (except the first)
for (i in 2:length(price)){
    if (r[i] > delta){
        signal[i] <- 1
    } else
      signal[i] <- 0
}
signal <- reclass(signal, price)
```


# Calculate the Daily Percentage Change on Filter
```{r}
trade <- Lag(signal, 1)
ret <- dailyReturn(MSFT) * trade
names(ret) <- "filter"
charts.PerformanceSummary(ret, main = "simple Filter")
```

# Calculate the RSI
```{r}
day <- 14
price <- MSFT$MSFT.Close
signal <- c(0)
rsi <- RSI(price, day)
```

# Create the rsi buyin signal
```{r}
signal[1:day + 1] <- 0

for (i in (day + 1):length(price)){
  if (rsi[i] < 40){
    signal[i] <- 1
  } else{
    signal[i] <- 0
  }
}
signal <- reclass(signal, MSFT$MSFT.Close)
```

# calculate the return
```{r}
trade2 <- Lag(signal)
ret2 <- dailyReturn(MSFT) * trade2
```

# Show the chart
```{r}
names(ret) <- "Simple"
names(ret2) <- "RSI"
retcomb <- cbind(ret, ret2)
charts.PerformanceSummary(retcomb, main = "Simple Filter vs RSI Filter")
```
